### ISSUE TITLE
Support for directly opening mp4?

### ISSUE THREAD

**Issue by fapdash** [crabshank/HTML5-media-speed-controller-subs#2]
First of all: thank you for making this awesome extension.
It's exactly what I'm looking for but currently it doesn't work for my use case.

## Specs

Chrome Version: Version 94.0.4606.61 (Official Build) (64-bit)
Extension: Version 1.51.2
I've given the extension access to file urls.
The extension is working as expected on youtube.

## Reproduction

Open an mp4 file in chrome either through file://myfile.mp4
Or through local web server: http://0.0.0.0:8000/myfile.mp4

## Expected

Control panel of extension shows up and the keybindings work (eg. speed up/down the video with `,` and `.`).

## Actual

Neither does the control panel show up nor do any of the keybindings work.
No output on the console.

**Comment by crabshank** [comment]
Works for me (as a local file), but if not for you then you can download [these webpages](https://github.com/crabshank/HTML5-media-player-webpages) and use "HTML5 Player (with speed control + colours) + WEBVTT SUBS.html" to open and play local files.
